export const jobListings = [
	{
		id: 1,
		title: "Software Engineer",
		company: "TechCorp",
		category: "Technology",
		location: "San Francisco, CA",
		logo: "/placeholder.svg",
		description:
			"Develop and maintain web applications, collaborate with cross-functional teams, and optimize system performance.",
		salary: "$100,000 - $120,000",
		employmentType: "Full-time",
		requirements: [
			"Proficiency in JavaScript, React, and Node.js",
			"Experience with RESTful APIs",
			"Strong problem-solving skills",
		],
		postedDate: "2025-02-15",
		applyLink: "https://techcorp.com/careers/software-engineer",
	},
	{
		id: 2,
		title: "Marketing Manager",
		company: "GrowthInc",
		category: "Marketing",
		location: "New York, NY",
		logo: "/placeholder.svg",
		description:
			"Lead marketing campaigns, analyze market trends, and drive brand growth through innovative strategies.",
		salary: "$80,000 - $95,000",
		employmentType: "Full-time",
		requirements: [
			"Experience in digital marketing and SEO",
			"Strong leadership and communication skills",
			"Ability to analyze marketing data",
		],
		postedDate: "2025-02-14",
		applyLink: "https://growthinc.com/jobs/marketing-manager",
	},
	{
		id: 3,
		title: "Sales Representative",
		company: "SalesPro",
		category: "Sales",
		location: "Chicago, IL",
		logo: "/placeholder.svg",
		description: "Manage client relationships, generate leads, and close sales to drive company revenue.",
		salary: "$60,000 - $75,000 (plus commission)",
		employmentType: "Full-time",
		requirements: [
			"Strong interpersonal and negotiation skills",
			"Experience in B2B sales",
			"Ability to meet sales targets",
		],
		postedDate: "2025-02-13",
		applyLink: "https://salespro.com/careers/sales-rep",
	},
	{
		id: 4,
		title: "Customer Support Specialist",
		company: "HelpDesk",
		category: "Customer Service",
		location: "Remote",
		logo: "/placeholder.svg",
		description: "Provide excellent customer support via chat, email, and phone, resolving issues efficiently.",
		salary: "$45,000 - $55,000",
		employmentType: "Remote",
		requirements: [
			"Strong communication skills",
			"Experience in customer service",
			"Ability to handle multiple support tickets",
		],
		postedDate: "2025-02-12",
		applyLink: "https://helpdesk.com/jobs/customer-support",
	},
	{
		id: 5,
		title: "Financial Analyst",
		company: "MoneyWise",
		category: "Finance",
		location: "Boston, MA",
		logo: "/placeholder.svg",
		description: "Analyze financial data, create reports, and provide insights to drive business decisions.",
		salary: "$85,000 - $100,000",
		employmentType: "Full-time",
		requirements: [
			"Strong analytical skills",
			"Experience with financial modeling",
			"Proficiency in Excel and financial software",
		],
		postedDate: "2025-02-11",
		applyLink: "https://moneywise.com/careers/financial-analyst",
	},
	{
		id: 6,
		title: "HR Coordinator",
		company: "PeopleFirst",
		category: "Human Resources",
		location: "Austin, TX",
		logo: "/placeholder.svg",
		description: "Support HR processes, manage recruitment, and ensure smooth employee relations.",
		salary: "$55,000 - $65,000",
		employmentType: "Full-time",
		requirements: [
			"Experience in HR processes",
			"Strong organizational and communication skills",
			"Knowledge of labor laws",
		],
		postedDate: "2025-02-10",
		applyLink: "https://peoplefirst.com/jobs/hr-coordinator",
	},
];
